version: '3.9'

services:
  db:
    image: postgres:15
    container_name: aerotec_postgres
    restart: always
    environment:
      POSTGRES_USER: batman
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: aerotecbd1
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    container_name: aerotec_django
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn djangocrud.wsgi:application --bind 0.0.0.0:${PORT:-8000}"
    environment:
      DJANGO_SETTINGS_MODULE: djangocrud.settings
      POSTGRES_DB: aerotecbd1
      POSTGRES_USER: batman
      POSTGRES_PASSWORD: qwe123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DEBUG: 'True'
      PORT: '8000'
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_data:/app/staticfiles
    depends_on:
      - db

volumes:
  db_data:
  static_data:
