# Generated by Django 5.1.1 on 2024-11-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vuelo', models.CharField(max_length=10, unique=True, verbose_name='Número de Vuelo')),
                ('aerolinea', models.CharField(max_length=50, verbose_name='Aerolínea')),
                ('modelo_avion', models.CharField(max_length=50, verbose_name='Modelo del Avión')),
                ('origen', models.CharField(max_length=100, verbose_name='Origen')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('tiempo_salida', models.DateTimeField(verbose_name='Fecha y Hora de Salida')),
                ('tiempo_llegada', models.DateTimeField(verbose_name='Fecha y Hora de Llegada')),
                ('duracion', models.DurationField(verbose_name='Duración Estimada')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Asiento')),
                ('asientos_disponibles', models.PositiveIntegerField(verbose_name='Asientos Disponibles')),
                ('asientos_totales', models.PositiveIntegerField(verbose_name='Asientos Totales')),
            ],
        ),
    ]
