# Generated by Django 5.1.1 on 2024-12-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_vuelos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=16, unique=True, verbose_name='Número de Tarjeta')),
                ('vigencia', models.CharField(max_length=5, verbose_name='Vigencia (MM/AA)')),
                ('cvv', models.CharField(max_length=3, verbose_name='CVV')),
            ],
        ),
    ]
