# Generated by Django 5.1.1 on 2024-12-02 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tarjeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='VuelosAgendados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vuelo', models.CharField(max_length=10, verbose_name='Número de Vuelo')),
                ('aerolinea', models.CharField(max_length=50, verbose_name='Aerolínea')),
                ('modelo_avion', models.CharField(max_length=50, verbose_name='Modelo del Avión')),
                ('origen', models.CharField(max_length=100, verbose_name='Origen')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('tiempo_salida', models.DateTimeField(verbose_name='Fecha y Hora de Salida')),
                ('tiempo_llegada', models.DateTimeField(verbose_name='Fecha y Hora de Llegada')),
                ('duracion', models.DurationField(verbose_name='Duración Estimada')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Asiento')),
                ('asientos_disponibles', models.PositiveIntegerField(verbose_name='Asientos Disponibles')),
                ('asientos_totales', models.PositiveIntegerField(verbose_name='Asientos Totales')),
                ('fecha_agendado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Agendado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
